In [1]:
import numpy as np

# randn函数返回一个或一组样本，具有标准正态分布
a = np.random.randn(5)
print(a)

[ 1.12783941 -0.98621401  0.67945101 -0.95293142  0.30347144]


In [2]:
# rand [0, 1)
b = np.random.rand(5)
print(b)

[0.30976591 0.15761357 0.46191303 0.86829499 0.18004099]


In [3]:
print(b.shape)

(5,)


In [7]:
# 看起来是和 a一样的
print(a.T)

[ 1.12783941 -0.98621401  0.67945101 -0.95293142  0.30347144]


In [6]:
# 其实是转置的。哈哈哈哈哈哈。
print(np.dot(a.T, a))
print(np.dot(a, a.T))

3.7064667123873023
3.7064667123873023


In [12]:
# 3 * 4 matrix
C = np.random.randn(3, 4)
print(C)

[[ 1.96483492  0.08478469  0.88291285 -1.11431926]
 [-0.6150558  -0.41147067  0.33629622  0.10540594]
 [-0.36626259 -0.88265429  1.58351547 -0.4337221 ]]


In [17]:
print(C.T)

[[ 1.96483492 -0.6150558  -0.36626259]
 [ 0.08478469 -0.41147067 -0.88265429]
 [ 0.88291285  0.33629622  1.58351547]
 [-1.11431926  0.10540594 -0.4337221 ]]


In [19]:
# 5*1
D = np.random.rand(5, 1)
print(D)

[[0.49733482]
 [0.35090472]
 [0.8952174 ]
 [0.86714882]
 [0.15607017]]


In [22]:
# 1 * 5 * 5 * 1
print(np.dot(D.T, D))

[[1.94819522]]
