In [1]:
# calculate percentage of each item

import numpy as np

# row: apple, beef, eggs, potatos
# column: carb, protein, fat
# apple: [56, 1.2, 1.8]


A = np.array([
    [56, 0.0, 4.4, 68.0],
    [1.2, 104.0, 52.0, 8.0],
    [1.8, 135.0, 99.0, 0.9]
])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [3]:
# 每一竖项相加
sumA = A.sum(axis = 0)

# 56 + 1.2 + 1.8 = 59
print(sumA)

[ 59.  239.  155.4  76.9]


In [8]:
# 56/59, 1.2/59, 1.8/59
sumA = A.sum(axis = 0)

percentage = 100 * A / sumA
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [9]:
print('=============')

In [10]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# B本来是 1 * 3matrix, 
# 因为相加 B [[100, 200, 300], [100, 200, 300]] 自动扩张到 2 * 3
B = np.array([100, 200, 300])

print(A + B)

[[101 202 303]
 [104 205 306]]
